/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import BL.BLCurso;
import BL.BLAsignacion;
import Clases.Curso;
import Clases.Tutor;
import Clases.Asignacion;
//import Validaciones.Validar;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rebec
 */
public class AsignarTut extends javax.swing.JFrame {

    ArrayList<Asignacion> ArrayAsignacion = new ArrayList<>();
    ArrayList<Curso> ArrayCurso = new ArrayList<>();
    ArrayList<Tutor> ArrayTutor = new ArrayList<>();
    
    BLCurso ObjBLCurso = new BLCurso();
    //BLDestino ObjBLDestino = new BLDestino();
    
    //Validar verificar = new Validar();
    
    static int codigo;
    
    String[] SCurso = {"", "Programacion", "Redes", "Microfinanzas", "Ingles", "Contabilidad", "Bioquímica"};
    String[] STutores1 = {"", "Israel Brito", "Santiago Ortega", "Carla Medina", "Patricio Cuenca", "Andrea Vivanco"};
    String[] STutores2 = {"", "Damian Jeréz", "Paulina Córdoba", "Luisa Cajamarca", "Mateo Mendoza"};
    String[] STutores3 = {"", "María Rodriguez", "Roberto Suarez", "Israel Sánchez", "Diego Calderón"};
    String[] STutores4 = {"", "Martha Barrera", "Emanuel Torres", "Leonel Luzuriaga", "Carlos Molina"};
    String[] STutores5 = {"", "Santiago Guevara", "Leonardo Calva", "Erick Bermeo", "Miriam Galvez"};
    String[] STutores6 = {"", "Samantha Lopez", "Enrique Alvarez", "Eduardo Moreira", "Jhosep Robayo"};

    public AsignarTut() throws ClassNotFoundException, SQLException {
        initComponents();
        
        
        ArrayCurso = ObjBLCurso.Consultar();
        this.comboCurso.removeAllItems();
        for (Curso ObjOrigen : ArrayCurso) {
            this.comboCurso.addItem(ObjOrigen.getNombre());
        }
        comboCurso.setModel(new javax.swing.DefaultComboBoxModel(SCurso));
        
        
//        ArrayTutor = ObjBLDestino.Consultar();
//        this.comboTutor.removeAllItems();
//        for (Tutor ObjDestino : ArrayTutor) {
//            this.comboTutor.addItem(ObjDestino.getNombre());
//        }
    }
    
    

    public void VaciarRegistros() {
        
        this.comboCurso.setSelectedItem("");
        this.comboTutor.setSelectedItem("");
        this.comboParalelo.setSelectedItem("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboParalelo = new javax.swing.JComboBox<>();
        comboCurso = new javax.swing.JComboBox<>();
        comboTutor = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(191, 220, 250));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asignar Tutor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Curso");
        jDesktopPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel4.setText("Tutor");
        jDesktopPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel5.setText("Paralelo");
        jDesktopPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        comboParalelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "A", "B", "A y B" }));
        jDesktopPane1.add(comboParalelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 120, -1));

        comboCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCursoActionPerformed(evt);
            }
        });
        jDesktopPane1.add(comboCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 370, -1));

        comboTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTutorActionPerformed(evt);
            }
        });
        jDesktopPane1.add(comboTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 370, -1));

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/avion.jpe"))); // NOI18N
        jDesktopPane1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 250, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDesktopPane1.getAccessibleContext().setAccessibleName("Asignar Tutor");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        MenuPrincipal view = new MenuPrincipal();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        VaciarRegistros();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (this.comboCurso.getSelectedItem().equals("") || this.comboTutor.getSelectedItem().equals("")
            || this.comboParalelo.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "POR FAVOR INGRESE TODOS LOS CAMPOS", "ASIGNACION DE TUTORES", JOptionPane.WARNING_MESSAGE);

        } else {
            BLAsignacion objBLAsignacion = new BLAsignacion();
            Curso ObjCurso = new Curso(this.comboCurso.getSelectedItem().toString());
            Tutor ObjTutor = new Tutor(this.comboTutor.getSelectedItem().toString());
            Asignacion objAsign = new Asignacion(0, ObjCurso, ObjTutor,
                this.comboParalelo.getSelectedItem().toString());

            ArrayAsignacion.add(objAsign);

            int resultado = 0;

            try {
                resultado = objBLAsignacion.InsertarAsign(objAsign);

                if (resultado == 1) {
                    JOptionPane.showMessageDialog(null, "DATOS REGISTRADOS");
                } else {
                    JOptionPane.showMessageDialog(null, "NO SE PUDO REGISTRAR");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AsignarTut.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AsignarTut.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        VaciarRegistros();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void comboTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTutorActionPerformed

    private void comboCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCursoActionPerformed
        // TODO add your handling code here:
        if (this.comboCurso.getSelectedItem().equals("Programacion")) {
            comboTutor.setModel(new javax.swing.DefaultComboBoxModel(STutores1));
        } else if (this.comboCurso.getSelectedItem().equals("Redes")) {
            comboTutor.setModel(new javax.swing.DefaultComboBoxModel(STutores2));
        } else if (this.comboCurso.getSelectedItem().equals("Microfinanzas")) {
            comboTutor.setModel(new javax.swing.DefaultComboBoxModel(STutores3));
        } else if (this.comboCurso.getSelectedItem().equals("Ingles")) {
            comboTutor.setModel(new javax.swing.DefaultComboBoxModel(STutores4));
        } else if (this.comboCurso.getSelectedItem().equals("Contabilidad")) {
            comboTutor.setModel(new javax.swing.DefaultComboBoxModel(STutores5));
        }else {
            comboTutor.setModel(new javax.swing.DefaultComboBoxModel(STutores6));
        }
    }//GEN-LAST:event_comboCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarTut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarTut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarTut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarTut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AsignarTut().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AsignarTut.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(AsignarTut.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboCurso;
    private javax.swing.JComboBox<String> comboParalelo;
    private javax.swing.JComboBox<String> comboTutor;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
